- name: Install Go
  snap:
    name: go
    classic: yes
  become: yes
- name: Create golang Dev Directory
  file:
    path: $HOME/go
    state: directory
- name: Create go/bin Directory
  file: 
    path: $HOME/go/bin
    state: directory
- name: Create go/src Directory
  file: 
    path: $HOME/go/src
    state: directory
- name: Create go/pkg Directory
  file: 
    path: $HOME/go/pkg
    state: directory
- name: Add GOBIN Environment Variable
  lineinfile:
    path: $HOME/.bash_profile
    regexp: '^export GOBIN'
    line: 'export GOBIN="$HOME/go/bin"'
- name: Add GOBIN Environment Variable
  lineinfile:
    path: $HOME/.bash_profile
    regexp: '^export GOPATH'
    line: 'export GOPATH="$HOME/go"'
- name: Load bash_profile
  shell: . $HOME/.bash_profile
