---
- name: Get NVM Installer
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: /tmp/nvm-install.sh
    mode: 0755
- name: Install NVM
  command: /tmp/nvm-install.sh
