# ansible-playbook -i "localhost," -c local linux.yml -K
#
# vim_plugins available:
#   stockhausenj/emmet-vim
#   stockhausenj/vim-javascript
#   stockhausenj/vim-pug
#   stockhausenj/vim-go
#
# Tested on CentOS7, Ubuntu 16.04
---
- hosts: all
  tasks: 
    - include_role:
        name: kubectl
      vars:
        version: '1.28.0'
    - include_role:
        name: git
      vars:
        git_user_email: 'jay.stockhausen@gmail.com'
        git_user_name: 'Jay Stockhausen'
    - include_role:
        name: tmux
    - include_role:
        name: vim
      vars:
        vim_plugins:
            - plug: 'scrooloose/nerdtree'
              branch: master
            - plug: 'mattn/emmet-vim'
              branch: master
            - plug: 'pangloss/vim-javascript'
              branch: master
            - plug: 'fatih/vim-go'
              branch: master
            - plug: 'python-mode/python-mode'
              branch: develop
    - include_role:
        name: bash
