# ansible-playbook -i "localhost," -c local macos.yml -K
---
- hosts: all
  tasks:
    - include_role:
        name: bash
    - include_role:
        name: kubectl
      vars:
        kubectl_version: "1.30.5"
