# ansible-playbook -i "localhost," -c local ubuntu.yml -K
#
# Tested on Ubuntu 22.04
---
- hosts: all
  tasks: 
    - include_role:
        name: bash
    - include_role:
        name: vim
    - include_role:
        name: tmux
    - include_role:
        name: git
      vars:
        git_user_email: 'jay.stockhausen@gmail.com'
        git_user_name: 'Jay Stockhausen'
    - include_role:
        name: kubectl
      vars:
        kubectl_version: '1.28.0'
        k9_version: '0.32.4'
        ndiff_version: '0.2.0'
    - include_role:
        name: nvm
      vars:
        nvm_version: '0.39.7'
